realizar_proposta:
  description: >
    Você está propondo a proposta: {proposta}
    Venha com um claro argumento em favor da proposta.
    Seja muito convincente.
  expected_output: >
    O seu argumento a favor da proposta, de uma maneira concisa.
  agent: debatedor
  output_file: output/proposta.md

negar_proposta:
  description: >
    Você está negando a proposta: {proposta}
    Venha com um claro argumento contra da proposta.
    Seja muito convincente.
  expected_output: >
    O seu argumento contra a proposta, de uma maneira concisa.
  agent: debatedor
  output_file: output/contra_proposta.md

decide:
  description: >
    Realizar uma análise dos argumentos apresentados pelos debatedores e decidir qual lado é mais convincente.
  expected_output: >
    O lado que você achou mais convincente, em conjunto com o motivo de você ter escolhido um dos lados.
  agent: juiz
  output_file: output/juiz.md
